// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A flow to clarify ambiguous voice commands with the user.
 *
 * - clarifyRequirements - A function that takes a potentially ambiguous command and clarifies it with the user.
 * - ClarifyRequirementsInput - The input type for the clarifyRequirements function.
 * - ClarifyRequirementsOutput - The return type for the clarifyRequirements function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const ClarifyRequirementsInputSchema = z.object({
  command: z.string().describe('The potentially ambiguous voice command.'),
});
export type ClarifyRequirementsInput = z.infer<typeof ClarifyRequirementsInputSchema>;

const ClarifyRequirementsOutputSchema = z.object({
  clarifiedCommand: z.string().describe('The clarified voice command after asking clarifying questions.'),
});
export type ClarifyRequirementsOutput = z.infer<typeof ClarifyRequirementsOutputSchema>;

export async function clarifyRequirements(input: ClarifyRequirementsInput): Promise<ClarifyRequirementsOutput> {
  return clarifyRequirementsFlow(input);
}

const clarifyRequirementsPrompt = ai.definePrompt({
  name: 'clarifyRequirementsPrompt',
  input: {
    schema: z.object({
      command: z.string().describe('The potentially ambiguous voice command.'),
    }),
  },
  output: {
    schema: z.object({
      clarifiedCommand: z.string().describe('The clarified voice command after asking clarifying questions.'),
    }),
  },
  prompt: `You are a helpful AI assistant that helps clarify ambiguous voice commands from the user.

The user has given the following voice command: {{{command}}}

If the command is ambiguous, you should ask clarifying questions to determine the user's intent.
If the command is clear, you should simply repeat the command.

Example 1:
User: "Move forward."
Assistant: "How many steps forward should I move?"

Example 2:
User: "Turn."
Assistant: "Which direction should I turn, left or right?"

Example 3:
User: "Move forward 5 steps."
Assistant: "Move forward 5 steps."

What clarifying questions should be asked, if any?  If there are no questions to ask, simply repeat the command to confirm.
`,
});

const clarifyRequirementsFlow = ai.defineFlow<
  typeof ClarifyRequirementsInputSchema,
  typeof ClarifyRequirementsOutputSchema
>({
  name: 'clarifyRequirementsFlow',
  inputSchema: ClarifyRequirementsInputSchema,
  outputSchema: ClarifyRequirementsOutputSchema,
},
async input => {
  const {output} = await clarifyRequirementsPrompt(input);
  return output!;
});

